# Header, all configurations related to dataloader will be under this header
dataloader:
  # Name of the dataloader to be used
  name: cub_200_2011
  # Flag in order to decide if to download the dataset or not
  download: False
  # The root directory path in case of Image Folder dataloader
  root_directory_path: /home/mm/PycharmProjects/SSL_for_FGVC/dataset/CUB_200_2011/
  # Image resize width
  resize_width: 448
  # Image resize height
  resize_height: 448
  # Batch size for training and testing
  batch_size: 64
  # Either to shuffle the dataset for training or not
  shuffle: True
  # Number of parallel workers to load the dataset
  num_workers: 8

# All configurations related to model will be under this header
model:
  # Name/source of the model
  name: torchvision
  # Complete function_path of the model (torchvision.models.resnet50, torchvision.models.alexnet, etc.)
  function_path: torchvision.models.resnet18
  # Either to load weights from pretrained imagenet model
  pretrained: True
  # Number of classes
  classes_count: 200
